/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/breakeven": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Breakeven */
        post: operations["breakeven_api_breakeven_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Builds */
        get: operations["list_builds_api_builds_get"];
        put?: never;
        /** Create Build */
        post: operations["create_build_api_builds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/builds/{build_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Build */
        get: operations["get_build_api_builds__build_id__get"];
        put?: never;
        post?: never;
        /** Delete Build */
        delete: operations["delete_build_api_builds__build_id__delete"];
        options?: never;
        head?: never;
        /** Update Build */
        patch: operations["update_build_api_builds__build_id__patch"];
        trace?: never;
    };
    "/api/builds/{build_id}/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate For Build
         * @description Run a saved build's stored attacks against a list of ACs -- same math
         *     as /api/calculate, just pulling the attacks from the database.
         */
        post: operations["calculate_for_build_api_builds__build_id__calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate */
        post: operations["calculate_api_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ACResult
         * @description A full round against one AC. `attacks` is in the same order as the
         *     request's attack list.
         */
        ACResult: {
            /** Ac */
            ac: number;
            /** Attacks */
            attacks: components["schemas"]["AttackResult"][];
            /** Total Had */
            total_had: number;
            /** Total Had Without Power Attack */
            total_had_without_power_attack: number | null;
        };
        /**
         * AttackEntry
         * @description One attack roll in a round, with everything that can differ between
         *     attacks -- including whether this particular attack uses power attack
         *     (GWM/Sharpshooter). A round is a list of these; repeat an entry for
         *     Extra Attack rather than using a count.
         */
        AttackEntry: {
            /**
             * Advantage
             * @default false
             */
            advantage: boolean;
            /** Attack Bonus */
            attack_bonus: number;
            /**
             * Crit Range
             * @default 20
             */
            crit_range: number;
            /** Die Sides */
            die_sides: number;
            /**
             * Disadvantage
             * @default false
             */
            disadvantage: boolean;
            /**
             * Modifier
             * @default 0
             */
            modifier: number;
            /**
             * Name
             * @default Attack
             */
            name: string;
            /** Num Dice */
            num_dice: number;
            /**
             * Power Attack
             * @default false
             */
            power_attack: boolean;
            /**
             * Power Attack Bonus
             * @default 0
             */
            power_attack_bonus: number;
            /**
             * Power Attack Penalty
             * @default 0
             */
            power_attack_penalty: number;
        };
        /**
         * AttackResult
         * @description One attack's numbers against one AC, with its own power-attack
         *     setting applied.
         */
        AttackResult: {
            /** Crit Chance */
            crit_chance: number;
            /** Had */
            had: number;
            /** Hit Chance */
            hit_chance: number;
        };
        /** BreakevenRequest */
        BreakevenRequest: {
            /**
             * Ac Max
             * @default 30
             */
            ac_max: number;
            /**
             * Ac Min
             * @default 1
             */
            ac_min: number;
            /**
             * Advantage
             * @default false
             */
            advantage: boolean;
            /** Attack Bonus */
            attack_bonus: number;
            /**
             * Crit Range
             * @default 20
             */
            crit_range: number;
            /** Die Sides */
            die_sides: number;
            /**
             * Disadvantage
             * @default false
             */
            disadvantage: boolean;
            /**
             * Modifier
             * @default 0
             */
            modifier: number;
            /** Num Dice */
            num_dice: number;
            /** Power Attack Bonus */
            power_attack_bonus: number;
            /** Power Attack Penalty */
            power_attack_penalty: number;
        };
        /** BreakevenResponse */
        BreakevenResponse: {
            /** Crossovers */
            crossovers: number[];
            /** Rows */
            rows: components["schemas"]["BreakevenRow"][];
        };
        /** BreakevenRow */
        BreakevenRow: {
            /** Ac */
            ac: number;
            /** Normal Had */
            normal_had: number;
            /** Power Had */
            power_had: number;
        };
        /**
         * BuildCalculateRequest
         * @description AC list to run a saved build's stored attacks against.
         */
        BuildCalculateRequest: {
            /** Ac List */
            ac_list: number[];
        };
        /**
         * BuildCreate
         * @description Everything required to save a new build.
         */
        BuildCreate: {
            /** Attacks */
            attacks: components["schemas"]["AttackEntry"][];
            /** Name */
            name: string;
        };
        /** BuildRead */
        BuildRead: {
            /** Attacks */
            attacks: components["schemas"]["AttackEntry"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * BuildUpdate
         * @description A partial update -- send only what changes. `attacks`, if sent,
         *     replaces the whole list.
         */
        BuildUpdate: {
            /** Attacks */
            attacks?: components["schemas"]["AttackEntry"][] | null;
            /** Name */
            name?: string | null;
        };
        /** CalculateRequest */
        CalculateRequest: {
            /** Ac List */
            ac_list: number[];
            /** Attacks */
            attacks: components["schemas"]["AttackEntry"][];
        };
        /** CalculateResponse */
        CalculateResponse: {
            /** Results */
            results: components["schemas"]["ACResult"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    breakeven_api_breakeven_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BreakevenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakevenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_builds_api_builds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildRead"][];
                };
            };
        };
    };
    create_build_api_builds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_build_api_builds__build_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_build_api_builds__build_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_build_api_builds__build_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_for_build_api_builds__build_id__calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                build_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildCalculateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_api_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
